In [10]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [11]:
tf.__version__

'2.12.0'

In [12]:
dataset = pd.read_csv('/content/drive/MyDrive/MSC CS/SEM 3/1. Machine Learning & Deep Learning/Practicals/10. Artificial Neural Network (ANN)/Churn_Modelling.csv')
x = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [13]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [14]:
print(y)

[1 0 1 ... 1 1 0]


# Encoding categorical data

In [15]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:, 2] = le.fit_transform(x[:, 2])

In [16]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


### One Hot Encoding the "Geography" column

In [17]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
x = np.array(ct.fit_transform(x))

In [18]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


# Splitting the dataset into the Training set and Test set

In [19]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

# Feature Scaling

In [20]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

# Part 2 - Building the ANN

In [21]:
ann = tf.keras.models.Sequential()

In [22]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

In [23]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

In [24]:
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

In [25]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [26]:
ann.fit(x_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 3s 5ms/step - loss: 0.5950 - accuracy: 0.7820
Epoch 2/100
250/250 [==============================] - 1s 6ms/step - loss: 0.4888 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 2s 7ms/step - loss: 0.4501 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 2s 6ms/step - loss: 0.4315 - accuracy: 0.8005
Epoch 5/100
250/250 [==============================] - 2s 7ms/step - loss: 0.4202 - accuracy: 0.8058
Epoch 6/100
250/250 [==============================] - 2s 7ms/step - loss: 0.4119 - accuracy: 0.8146
Epoch 7/100
250/250 [==============================] - 1s 5ms/step - loss: 0.4044 - accuracy: 0.8221
Epoch 8/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3968 - accuracy: 0.8270
Epoch 9/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3892 - accuracy: 0.8319
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3823 - accura

In [27]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) >0.5)

1/1 [==============================] - 0s 238ms/step
[[False]]


In [28]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 2ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [29]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1527   68]
 [ 205  200]]


0.8635